config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :user, :controllers => { :sessions => "devise/sessions" }, :skip => [:registrations]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'users#show'
  resources :transactions, only: %i(create new show)
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user, class_name: "User", foreign_key: "user_id"
  validates :balance, numericality: { greater_than_or_equal_to: 0 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :from, :class_name => 'Account', :foreign_key => :from_id
  belongs_to :to, :class_name => 'Account', :foreign_key => :to_id

  TYPES_ALLOWED = %w(deposite transfer)

  validates_presence_of :to_id, :from_id, :amount, :variety
  validates :variety, inclusion: { in: TYPES_ALLOWED }
  validates :amount, numericality: { greater_than: 0 }

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :account

  before_create :set_up_account

  validates :email, presence: true
  validates :email, uniqueness: { case_sensitive: false }

  def self.create_user(email, password)
    user = User.new(email: email, password: password)
    user.save
  end

  def self.add_deposite(user_id, amount)
    transaction = Transactions::CreateDepositeService.call(
      amount: amount,
      to_id: user_id,
      from_id: user_id
    )
    puts transaction.errors if transaction.failure?
  end

  def set_up_account
    self.account = Account.new
  end

  def transactions
    Transaction.includes(from: :user, to: :user)
      .where('from_id = :id or to_id = :id', { id: id })
      .order(created_at: :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    root_path
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :find_transaction, only: %i(show)

  def new
    @transaction = Transaction.new
    @users = User.where.not(id: current_user.id).pluck(:email, :id)
  end

  def create
    @transaction = Transactions::CreateTransferService.call(
      transaction_params.to_unsafe_h.merge(
        { from_id: current_user.id }
      )
    )

    if @transaction.failure?
      flash[:alert] = @transaction.errors.join(', ')
    else
      flash[:notice] = 'operation successed'
      redirect_to transaction_path(id: @transaction.transaction.id)
    end
  end

  def show; end

  private

  def find_transaction
    @transaction = Transaction.find_by(id: params[:id])
    check_permissions
  end

  def check_permissions
    unless [@transaction.from_id, @transaction.to_id].include?(current_user.account.id)
      flash[:alert] = 'permission denied'
      redirect_to root_path
    end
  end

  def transaction_params
    params.require(:transaction).permit(:to_id, :amount)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @transactions = current_user.transactions
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BankApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/transactions/new.html.haml
Send money

= form_tag({:action => "create"}) do
  Amount
  = number_field 'transaction', 'amount', step: 0.01
  %br
  Currency
  = select_tag "transaction[to_id]", options_for_select(@users)
  %br
  = submit_tag "Send"

app/views/transactions/show.html.haml
%ul
  %li= @transaction.amount
  %li= @transaction.id
  %li= @transaction.created_at

app/views/users/show.html.haml
%h1= "Hello, #{current_user.email}"

= link_to 'send money', new_transaction_path

Transactions history
%table
  %thead
    %tr
      %th{scope: "col"} From
      %th{scope: "col"} To
      %th{scope: "col"} Amount
      %th{scope: "col"} Details

  %tbody
    - @transactions.each do |transaction|
      %tr
        %td= transaction.from.user.email
        %td= transaction.to.user.email
        %td= transaction.amount
        %td= link_to 'more info', transaction_path(id: transaction.id)